### ISSUE TITLE
Cannot install webhooks because of sideEffects value

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-helm-chart#5]
Cannot install `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` because of `sideEffects=Unknown`.

`Error: MutatingWebhookConfiguration.admissionregistration.k8s.io "capsule-mutating-webhook-configuration" is invalid: [webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun", webhooks[1].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"]`

As the Webhooks Configuration manifests are in `apiVersion: admissionregistration.k8s.io/v1`, we have to use a proper value as per [documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects): `None` or `NoneOnDryRun`.

**Comment by MaxFedotov** [comment]
closed by #11
